# Generated by Django 6.0.5 on 2026-05-07 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('requester', 'Demandeur'), ('purchasing', 'Équipe Achats'), ('director', 'Directeur (DG)')], default='requester', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('assignment', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Commandé', 'Commandé'), ('Reçu', 'Reçu'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
