# Generated by Django 6.0.5 on 2026-05-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catalogue Fournisseur',
                'verbose_name_plural': 'Catalogue Fournisseurs',
                'unique_together': {('product_name', 'supplier_name')},
            },
        ),
    ]
