# Generated by Django 6.0.5 on 2026-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_suppliercatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='refusal_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
