# Generated by Django 6.0.5 on 2026-06-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_quotecomparisonhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='request_pdf',
            field=models.FileField(blank=True, null=True, upload_to='requests_pdf/'),
        ),
    ]
