services:
  # 1. Base de données PostgreSQL
  db:
    image: postgres:16
    container_name: project_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  # 2. Backend Django API
  backend:
    build: ./backend
    container_name: project_backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_REGION=${GOOGLE_CLOUD_REGION}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    depends_on:
      - db
    restart: always

  # 3. Frontend React + Nginx + HTTPS
  frontend:
    build: ./frontend
    container_name: project_frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
